#!/bin/sh

CMD="$*"
OPTS='-t '

ssh_cmd () {
    if [ -x "$(which autossh)" ]; then
        echo 'autossh -M 0'
    else
        echo 'ssh'
    fi
}

host=$(awk '$2 !~ /^\*/ && /^Host/ {sub(/\*$/,""); print $2}' ~/.ssh/config \
    | dmenu)

[ -z "$host" ] && exit

eval urxvtc -e "$(ssh_cmd)" "$OPTS" "$host" "$CMD"
#eval urxvtc -title "ssh $host" -e "$(ssh_cmd)" "$OPTS" "$host" "$CMD"
